[all]
192.168.39.60 ansible_host=192.168.39.60 ip=192.168.39.60 ansible_user=installadm ansible_ssh_pass=FfAaJjDd@05*26 ansible_become_password=FfAaJjDd@05*26 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
192.168.39.61 ansible_host=192.168.39.61 ip=192.168.39.61 ansible_user=installadm ansible_ssh_pass=FfAaJjDd@05*26 ansible_become_password=FfAaJjDd@05*26 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
192.168.39.62 ansible_host=192.168.39.62 ip=192.168.39.62 ansible_user=installadm ansible_ssh_pass=FfAaJjDd@05*26 ansible_become_password=FfAaJjDd@05*26 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
192.168.39.63 ansible_host=192.168.39.63 ip=192.168.39.63 ansible_user=installadm ansible_ssh_pass=FfAaJjDd@05*26 ansible_become_password=FfAaJjDd@05*26 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
192.168.39.64 ansible_host=192.168.39.64 ip=192.168.39.64 ansible_user=installadm ansible_ssh_pass=FfAaJjDd@05*26 ansible_become_password=FfAaJjDd@05*26 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
192.168.39.65 ansible_host=192.168.39.65 ip=192.168.39.65 ansible_user=installadm ansible_ssh_pass=FfAaJjDd@05*26 ansible_become_password=FfAaJjDd@05*26 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[kube_control_plane]
192.168.39.60
192.168.39.61
192.168.39.62

[etcd]
192.168.39.60
192.168.39.61
192.168.39.62

[kube_node]
192.168.39.63
192.168.39.64
192.168.39.65

[k8s_cluster:children]
kube_control_plane
kube_node