---
- name: Install Kubernetes Components
  hosts: all
  become: yes
  tasks:
    - name: Check if /etc/apt/keyrings directory exists, create if not
      shell: ls -d /etc/apt/keyrings 2> /dev/null || sudo mkdir -p -m 755 /etc/apt/keyrings
      changed_when: false

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages for Kubernetes repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    - name: Download Kubernetes GPG key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /'
        create: yes

    - name: Update package cache after adding Kubernetes repository
      apt:
        update_cache: yes

    - name: Check available kubeadm versions
      shell: apt-cache madison kubeadm
      register: kubeadm_versions
      changed_when: false

    - name: Display available kubeadm versions
      debug:
        msg: "Available kubeadm versions: {{ kubeadm_versions.stdout_lines }}"

    - name: Install kubelet, kubeadm, kubectl
      apt:
        name:
          - kubelet=1.31.0-1.1
          - kubeadm=1.31.0-1.1
          - kubectl=1.31.0-1.1
        state: present

    - name: Hold kubelet, kubeadm, kubectl packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Check kubeadm version
      command: kubeadm version
      register: kubeadm_version_check
      changed_when: false

    - name: Display kubeadm version
      debug:
        msg: "{{ kubeadm_version_check.stdout }}"

    - name: Check kubelet version
      command: kubelet --version
      register: kubelet_version_check
      changed_when: false

    - name: Display kubelet version
      debug:
        msg: "{{ kubelet_version_check.stdout }}"

    - name: Check kubectl version
      command: kubectl version --client
      register: kubectl_version_check
      changed_when: false

    - name: Display kubectl version
      debug:
        msg: "{{ kubectl_version_check.stdout }}" 