#05-master-init.yml

---
- name: Initialize Kubernetes Master Node
  hosts: masters
  become: yes
  tasks:
    - name: Initialize Kubernetes cluster with kubeadm
      shell: |
        kubeadm init \
          --apiserver-advertise-address {{ ansible_default_ipv4.address }} \
          --control-plane-endpoint "k8s-lb.example.com:6443" \
          --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init_result

    - name: Display kubeadm init output
      debug:
        msg: "{{ kubeadm_init_result.stdout_lines }}"

    - name: Create .kube directory for regular user
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Create .kube directory for root user
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        mode: '0644'

    - name: Extract join command from kubeadm init output
      shell: echo "{{ kubeadm_init_result.stdout }}" | grep -A 2 "kubeadm join"
      register: join_command_raw
      changed_when: false

    - name: Save join command to file
      copy:
        content: "{{ join_command_raw.stdout }}"
        dest: /tmp/kubeadm_join_command.sh
        mode: '0755'

    - name: Display join command
      debug:
        msg: |
          Master node initialized successfully!
          
          Join command for worker nodes:
          {{ join_command_raw.stdout }}
          
          The join command has been saved to /tmp/kubeadm_join_command.sh 