---
- name: Configure HAProxy as Kubernetes API Load Balancer
  hosts: haproxy
  become: yes
  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Deploy HAProxy config
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          frontend k8s-api
              bind *:6443
              default_backend k8s-masters

          backend k8s-masters
              balance roundrobin
              option httpchk GET /healthz
              http-check expect status 200
              server master1 10.10.7.2:6443 check
              server master2 10.10.7.3:6443 check
              server master3 10.10.7.4:6443 check
        mode: '0644'

    - name: Enable and restart HAProxy
      service:
        name: haproxy
        enabled: yes
        state: restarted
