---
- name: Configure HAProxy as Kubernetes API Load Balancer
  hosts: masters
  become: yes
  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Deploy HAProxy config to /etc/haproxy/haproxy.cfg
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          global
              log /dev/log local0
              maxconn 2048
              daemon

          defaults
              log     global
              mode    tcp
              option  tcplog
              timeout connect 10s
              timeout client  30s
              timeout server  30s

          frontend k8s-api
              bind 10.10.7.17:6443
              default_backend k8s-masters

          backend k8s-masters
              balance roundrobin
              option tcp-check
              server master1 10.10.7.12:6443 check
              server master2 10.10.7.13:6443 check
              server master3 10.10.7.14:6443 check
        mode: '0644'

    - name: Restart and enable HAProxy
      service:
        name: haproxy
        state: restarted
        enabled: yes

    - name: Check HAProxy status
      shell: systemctl status haproxy --no-pager
      register: haproxy_status
      changed_when: false

    - name: Display HAProxy status
      debug:
        msg: "{{ haproxy_status.stdout_lines }}"