---
- name: Copy kubeconfig from master-1 to other nodes
  hosts: masters[1:]
  become: yes
  tasks:
    - name: Fetch admin.conf from master-1
      delegate_to: "{{ groups['masters'][0] }}"
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/admin.conf
        flat: yes

    - name: Create .kube directory for user
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /tmp/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Create .kube directory for root
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Ensure root also has kubeconfig
      copy:
        src: /tmp/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root
        mode: '0644'
